[phases.setup]
runtime = ["python", "nodejs"]
commands = [
    "apt-get update && apt-get install -y python3 python3-pip"
]

[phases.build]
commands = [
    "python3 -m pip install --upgrade pip",
    "pip install -r requirements.txt",
    "npm install",
    "npm run build:css"
]

[start]
cmd = "gunicorn main:app"
